# cloudbuild.yaml
steps:
  # Instalar dependencias
  - name: 'node:20'
    entrypoint: 'yarn'
    args: ['install']

  # Ejecutar pruebas
  - name: 'node:20'
    entrypoint: 'yarn'
    args: ['test']

  # Construir la aplicación
  - name: 'node:20'
    entrypoint: 'yarn'
    args: ['build']

  # Construir la imagen Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/siembraco-repo/siembraco-api:$SHORT_SHA',
      '.'
    ]

  # Publicar la imagen en Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/siembraco-repo/siembraco-api:$SHORT_SHA']

  # Desplegar a Cloud Run (versión simplificada)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: [
      'run', 'deploy', 'siembraco-api',
      '--image', 'us-central1-docker.pkg.dev/$PROJECT_ID/siembraco-repo/siembraco-api:$SHORT_SHA',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated'
    ]

# Opciones
timeout: '1800s'
