FROM node:20-alpine

WORKDIR /usr/src/app

# Copia primero el package.json y yarn.lock
COPY package.json yarn.lock ./
RUN yarn install

# Copia primero el archivo .env si existe
COPY .env* ./

# Luego copia el resto del código
COPY . .

EXPOSE 3000

CMD ["yarn", "start:dev"]