services:
  siembraco-api-dev:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - FIREBASE_PROJECT_ID=siembraco-api-fr
      - FIREBASE_CLIENT_EMAIL=firebase-adminsdk-fbsvc@siembraco-api-fr.iam.gserviceaccount.com
      # No incluyas la PRIVATE_KEY aquí directamente por seguridad
    env_file:
      - .env  # Cargar el resto desde el archivo .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: yarn start:dev